# Generated by Django 4.2.7 on 2023-11-11 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_deposito_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposito',
            name='data',
        ),
    ]
