# Generated by Django 4.2.7 on 2023-11-15 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='saldo',
        ),
    ]
