# Generated by Django 4.2.7 on 2023-11-15 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_userprofile_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='deposito',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.deposito'),
            preserve_default=False,
        ),
    ]
